name: ER Statistics CI
# trigger
on:
  push:
    branches: [bug*]
  pull_request_target:
    branches: [main,develop]
    types: [labeled]
# jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.base.sha}}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: Chmod Permission to python files
        run: sudo chmod +x project_setting.py
      - name: pip installation
        run: pip install -r requirements.txt
      - name: running test code
        run: python test.py
      - name: running project setting
        run: python project_setting.py ${{secrets.ER_API_KEY}}

  build:
    name: test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.base.sha}}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: pip installation
        run: pip install -r requirements.txt
      - name: running test code
        run: python test.py
      - name: running project setting
        run: python project_setting.py ${{secrets.ER_API_KEY}}