name: pr_test_code
on:
  pull_request_target:
      branches: [main,develop]
      types: [labeled]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.base.sha}}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: running project setting
        run: python project_setting.py ${{ ER_API_KEY }}
      - name: running test code
        run: python test.py
