name: EC2 / Docker CI
# trigger
on:
  push:
    branches: [main, develop]
permissions:
  contents: read

# jobs
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature_EC2')
    steps:
      # - name: Create env file
      #   run:  |
      #     touch .env
      #     echo "${{secrets.ENV_VARS }}" >> .env
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"
      
      - name: Get git actions IP
        id: ip
        uses: haythem/public-ip@v1.2      

      # - name: pip installation
      #   run: pip install -r requirements.txt
      
      # # docker build & push to main
      # - name: Docker build & push to main
      #   if: contains(github.ref, 'main')
      #   run:  |
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-test-main .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/docker-test-main
      # # docker build & push to develop
      # - name: Docker build & push to develop
      #    if: contains(github.ref, 'develop')
      #   run: |
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-test-dev .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/docker-test-dev

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      # Add github ip to AWS
      - name: Add GitHub IP to AWS
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      
      # AWS EC2 Server Connect & Docker run
      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker stop docker-test-dev
            sudo docker rm docker-test-dev
            sudo docker run -it -d -p 8080:8080 --name docker-test-dev ${{ secrets.DOCKER_USERNAME }}/docker-test-dev